// This file was auto-generated by Fern from our API Definition.

package client

import (
	http "net/http"
	assets "sdk/assets"
	core "sdk/core"
	decisions "sdk/decisions"
	flows "sdk/flows"
	option "sdk/option"
	rules "sdk/rules"
	tests "sdk/tests"
	users "sdk/users"
	values "sdk/values"
)

type Client struct {
	baseURL string
	caller  *core.Caller
	header  http.Header

	Rules     *rules.Client
	Flows     *flows.Client
	Decisions *decisions.Client
	Assets    *assets.Client
	Users     *users.Client
	Tests     *tests.Client
	Values    *values.Client
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		baseURL: options.BaseURL,
		caller: core.NewCaller(
			&core.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
		header:    options.ToHeader(),
		Rules:     rules.NewClient(opts...),
		Flows:     flows.NewClient(opts...),
		Decisions: decisions.NewClient(opts...),
		Assets:    assets.NewClient(opts...),
		Users:     users.NewClient(opts...),
		Tests:     tests.NewClient(opts...),
		Values:    values.NewClient(opts...),
	}
}
