// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
	time "time"
)

func TestSettersQueryDecisionsRequest(t *testing.T) {
	t.Run("SetSearch", func(t *testing.T) {
		obj := &QueryDecisionsRequest{}
		var fernTestValueSearch *string
		obj.SetSearch(fernTestValueSearch)
		assert.Equal(t, fernTestValueSearch, obj.Search)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetRules", func(t *testing.T) {
		obj := &QueryDecisionsRequest{}
		var fernTestValueRules *string
		obj.SetRules(fernTestValueRules)
		assert.Equal(t, fernTestValueRules, obj.Rules)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetFlows", func(t *testing.T) {
		obj := &QueryDecisionsRequest{}
		var fernTestValueFlows *string
		obj.SetFlows(fernTestValueFlows)
		assert.Equal(t, fernTestValueFlows, obj.Flows)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetContexts", func(t *testing.T) {
		obj := &QueryDecisionsRequest{}
		var fernTestValueContexts *string
		obj.SetContexts(fernTestValueContexts)
		assert.Equal(t, fernTestValueContexts, obj.Contexts)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetTrace", func(t *testing.T) {
		obj := &QueryDecisionsRequest{}
		var fernTestValueTrace *string
		obj.SetTrace(fernTestValueTrace)
		assert.Equal(t, fernTestValueTrace, obj.Trace)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetStatuses", func(t *testing.T) {
		obj := &QueryDecisionsRequest{}
		var fernTestValueStatuses *string
		obj.SetStatuses(fernTestValueStatuses)
		assert.Equal(t, fernTestValueStatuses, obj.Statuses)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetIncludeTraces", func(t *testing.T) {
		obj := &QueryDecisionsRequest{}
		var fernTestValueIncludeTraces *QueryDecisionsRequestIncludeTraces
		obj.SetIncludeTraces(fernTestValueIncludeTraces)
		assert.Equal(t, fernTestValueIncludeTraces, obj.IncludeTraces)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetItemFilter", func(t *testing.T) {
		obj := &QueryDecisionsRequest{}
		var fernTestValueItemFilter *string
		obj.SetItemFilter(fernTestValueItemFilter)
		assert.Equal(t, fernTestValueItemFilter, obj.ItemFilter)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetStart", func(t *testing.T) {
		obj := &QueryDecisionsRequest{}
		var fernTestValueStart *time.Time
		obj.SetStart(fernTestValueStart)
		assert.Equal(t, fernTestValueStart, obj.Start)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetEnd", func(t *testing.T) {
		obj := &QueryDecisionsRequest{}
		var fernTestValueEnd *time.Time
		obj.SetEnd(fernTestValueEnd)
		assert.Equal(t, fernTestValueEnd, obj.End)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetSort", func(t *testing.T) {
		obj := &QueryDecisionsRequest{}
		var fernTestValueSort *QueryDecisionsRequestSort
		obj.SetSort(fernTestValueSort)
		assert.Equal(t, fernTestValueSort, obj.Sort)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetOrder", func(t *testing.T) {
		obj := &QueryDecisionsRequest{}
		var fernTestValueOrder *QueryDecisionsRequestOrder
		obj.SetOrder(fernTestValueOrder)
		assert.Equal(t, fernTestValueOrder, obj.Order)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetCursor", func(t *testing.T) {
		obj := &QueryDecisionsRequest{}
		var fernTestValueCursor *string
		obj.SetCursor(fernTestValueCursor)
		assert.Equal(t, fernTestValueCursor, obj.Cursor)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetLimit", func(t *testing.T) {
		obj := &QueryDecisionsRequest{}
		var fernTestValueLimit *int
		obj.SetLimit(fernTestValueLimit)
		assert.Equal(t, fernTestValueLimit, obj.Limit)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetCount", func(t *testing.T) {
		obj := &QueryDecisionsRequest{}
		var fernTestValueCount *QueryDecisionsRequestCount
		obj.SetCount(fernTestValueCount)
		assert.Equal(t, fernTestValueCount, obj.Count)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitQueryDecisionsRequest(t *testing.T) {
	t.Run("SetSearch_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &QueryDecisionsRequest{}
		var fernTestValueSearch *string

		// Act
		obj.SetSearch(fernTestValueSearch)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetRules_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &QueryDecisionsRequest{}
		var fernTestValueRules *string

		// Act
		obj.SetRules(fernTestValueRules)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetFlows_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &QueryDecisionsRequest{}
		var fernTestValueFlows *string

		// Act
		obj.SetFlows(fernTestValueFlows)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetContexts_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &QueryDecisionsRequest{}
		var fernTestValueContexts *string

		// Act
		obj.SetContexts(fernTestValueContexts)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetTrace_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &QueryDecisionsRequest{}
		var fernTestValueTrace *string

		// Act
		obj.SetTrace(fernTestValueTrace)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetStatuses_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &QueryDecisionsRequest{}
		var fernTestValueStatuses *string

		// Act
		obj.SetStatuses(fernTestValueStatuses)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetIncludeTraces_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &QueryDecisionsRequest{}
		var fernTestValueIncludeTraces *QueryDecisionsRequestIncludeTraces

		// Act
		obj.SetIncludeTraces(fernTestValueIncludeTraces)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetItemFilter_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &QueryDecisionsRequest{}
		var fernTestValueItemFilter *string

		// Act
		obj.SetItemFilter(fernTestValueItemFilter)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetStart_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &QueryDecisionsRequest{}
		var fernTestValueStart *time.Time

		// Act
		obj.SetStart(fernTestValueStart)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetEnd_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &QueryDecisionsRequest{}
		var fernTestValueEnd *time.Time

		// Act
		obj.SetEnd(fernTestValueEnd)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetSort_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &QueryDecisionsRequest{}
		var fernTestValueSort *QueryDecisionsRequestSort

		// Act
		obj.SetSort(fernTestValueSort)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetOrder_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &QueryDecisionsRequest{}
		var fernTestValueOrder *QueryDecisionsRequestOrder

		// Act
		obj.SetOrder(fernTestValueOrder)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetCursor_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &QueryDecisionsRequest{}
		var fernTestValueCursor *string

		// Act
		obj.SetCursor(fernTestValueCursor)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetLimit_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &QueryDecisionsRequest{}
		var fernTestValueLimit *int

		// Act
		obj.SetLimit(fernTestValueLimit)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetCount_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &QueryDecisionsRequest{}
		var fernTestValueCount *QueryDecisionsRequestCount

		// Act
		obj.SetCount(fernTestValueCount)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersDecisionLog(t *testing.T) {
	t.Run("SetTimestamp", func(t *testing.T) {
		obj := &DecisionLog{}
		var fernTestValueTimestamp *time.Time
		obj.SetTimestamp(fernTestValueTimestamp)
		assert.Equal(t, fernTestValueTimestamp, obj.Timestamp)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetName", func(t *testing.T) {
		obj := &DecisionLog{}
		var fernTestValueName *string
		obj.SetName(fernTestValueName)
		assert.Equal(t, fernTestValueName, obj.Name)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetEndpoint", func(t *testing.T) {
		obj := &DecisionLog{}
		var fernTestValueEndpoint *string
		obj.SetEndpoint(fernTestValueEndpoint)
		assert.Equal(t, fernTestValueEndpoint, obj.Endpoint)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetStatus", func(t *testing.T) {
		obj := &DecisionLog{}
		var fernTestValueStatus *int
		obj.SetStatus(fernTestValueStatus)
		assert.Equal(t, fernTestValueStatus, obj.Status)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetRequest", func(t *testing.T) {
		obj := &DecisionLog{}
		var fernTestValueRequest *DecisionLogRequest
		obj.SetRequest(fernTestValueRequest)
		assert.Equal(t, fernTestValueRequest, obj.Request)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetResponse", func(t *testing.T) {
		obj := &DecisionLog{}
		var fernTestValueResponse *DecisionLogResponse
		obj.SetResponse(fernTestValueResponse)
		assert.Equal(t, fernTestValueResponse, obj.Response)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetDecision", func(t *testing.T) {
		obj := &DecisionLog{}
		var fernTestValueDecision map[string]any
		obj.SetDecision(fernTestValueDecision)
		assert.Equal(t, fernTestValueDecision, obj.Decision)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetTraceID", func(t *testing.T) {
		obj := &DecisionLog{}
		var fernTestValueTraceID *string
		obj.SetTraceID(fernTestValueTraceID)
		assert.Equal(t, fernTestValueTraceID, obj.TraceID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPathTrace", func(t *testing.T) {
		obj := &DecisionLog{}
		var fernTestValuePathTrace *DecisionLogPathTrace
		obj.SetPathTrace(fernTestValuePathTrace)
		assert.Equal(t, fernTestValuePathTrace, obj.PathTrace)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetMatchedItems", func(t *testing.T) {
		obj := &DecisionLog{}
		var fernTestValueMatchedItems []int
		obj.SetMatchedItems(fernTestValueMatchedItems)
		assert.Equal(t, fernTestValueMatchedItems, obj.MatchedItems)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetError", func(t *testing.T) {
		obj := &DecisionLog{}
		var fernTestValueError *string
		obj.SetError(fernTestValueError)
		assert.Equal(t, fernTestValueError, obj.Error)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetAbbreviated", func(t *testing.T) {
		obj := &DecisionLog{}
		var fernTestValueAbbreviated *bool
		obj.SetAbbreviated(fernTestValueAbbreviated)
		assert.Equal(t, fernTestValueAbbreviated, obj.Abbreviated)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersDecisionLog(t *testing.T) {
	t.Run("GetTimestamp", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DecisionLog{}
		var expected *time.Time
		obj.Timestamp = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetTimestamp(), "getter should return the property value")
	})

	t.Run("GetTimestamp_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DecisionLog{}
		obj.Timestamp = nil

		// Act & Assert
		assert.Nil(t, obj.GetTimestamp(), "getter should return nil when property is nil")
	})

	t.Run("GetTimestamp_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *DecisionLog
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetTimestamp() // Should return zero value
	})

	t.Run("GetName", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DecisionLog{}
		var expected *string
		obj.Name = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetName(), "getter should return the property value")
	})

	t.Run("GetName_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DecisionLog{}
		obj.Name = nil

		// Act & Assert
		assert.Nil(t, obj.GetName(), "getter should return nil when property is nil")
	})

	t.Run("GetName_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *DecisionLog
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetName() // Should return zero value
	})

	t.Run("GetEndpoint", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DecisionLog{}
		var expected *string
		obj.Endpoint = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetEndpoint(), "getter should return the property value")
	})

	t.Run("GetEndpoint_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DecisionLog{}
		obj.Endpoint = nil

		// Act & Assert
		assert.Nil(t, obj.GetEndpoint(), "getter should return nil when property is nil")
	})

	t.Run("GetEndpoint_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *DecisionLog
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetEndpoint() // Should return zero value
	})

	t.Run("GetStatus", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DecisionLog{}
		var expected *int
		obj.Status = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetStatus(), "getter should return the property value")
	})

	t.Run("GetStatus_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DecisionLog{}
		obj.Status = nil

		// Act & Assert
		assert.Nil(t, obj.GetStatus(), "getter should return nil when property is nil")
	})

	t.Run("GetStatus_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *DecisionLog
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetStatus() // Should return zero value
	})

	t.Run("GetRequest", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DecisionLog{}
		var expected *DecisionLogRequest
		obj.Request = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetRequest(), "getter should return the property value")
	})

	t.Run("GetRequest_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DecisionLog{}
		obj.Request = nil

		// Act & Assert
		assert.Nil(t, obj.GetRequest(), "getter should return nil when property is nil")
	})

	t.Run("GetRequest_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *DecisionLog
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetRequest() // Should return zero value
	})

	t.Run("GetResponse", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DecisionLog{}
		var expected *DecisionLogResponse
		obj.Response = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetResponse(), "getter should return the property value")
	})

	t.Run("GetResponse_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DecisionLog{}
		obj.Response = nil

		// Act & Assert
		assert.Nil(t, obj.GetResponse(), "getter should return nil when property is nil")
	})

	t.Run("GetResponse_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *DecisionLog
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetResponse() // Should return zero value
	})

	t.Run("GetDecision", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DecisionLog{}
		var expected map[string]any
		obj.Decision = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetDecision(), "getter should return the property value")
	})

	t.Run("GetDecision_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DecisionLog{}
		obj.Decision = nil

		// Act & Assert
		assert.Nil(t, obj.GetDecision(), "getter should return nil when property is nil")
	})

	t.Run("GetDecision_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *DecisionLog
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetDecision() // Should return zero value
	})

	t.Run("GetTraceID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DecisionLog{}
		var expected *string
		obj.TraceID = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetTraceID(), "getter should return the property value")
	})

	t.Run("GetTraceID_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DecisionLog{}
		obj.TraceID = nil

		// Act & Assert
		assert.Nil(t, obj.GetTraceID(), "getter should return nil when property is nil")
	})

	t.Run("GetTraceID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *DecisionLog
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetTraceID() // Should return zero value
	})

	t.Run("GetPathTrace", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DecisionLog{}
		var expected *DecisionLogPathTrace
		obj.PathTrace = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetPathTrace(), "getter should return the property value")
	})

	t.Run("GetPathTrace_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DecisionLog{}
		obj.PathTrace = nil

		// Act & Assert
		assert.Nil(t, obj.GetPathTrace(), "getter should return nil when property is nil")
	})

	t.Run("GetPathTrace_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *DecisionLog
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetPathTrace() // Should return zero value
	})

	t.Run("GetMatchedItems", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DecisionLog{}
		var expected []int
		obj.MatchedItems = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetMatchedItems(), "getter should return the property value")
	})

	t.Run("GetMatchedItems_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DecisionLog{}
		obj.MatchedItems = nil

		// Act & Assert
		assert.Nil(t, obj.GetMatchedItems(), "getter should return nil when property is nil")
	})

	t.Run("GetMatchedItems_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *DecisionLog
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetMatchedItems() // Should return zero value
	})

	t.Run("GetError", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DecisionLog{}
		var expected *string
		obj.Error = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetError(), "getter should return the property value")
	})

	t.Run("GetError_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DecisionLog{}
		obj.Error = nil

		// Act & Assert
		assert.Nil(t, obj.GetError(), "getter should return nil when property is nil")
	})

	t.Run("GetError_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *DecisionLog
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetError() // Should return zero value
	})

	t.Run("GetAbbreviated", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DecisionLog{}
		var expected *bool
		obj.Abbreviated = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetAbbreviated(), "getter should return the property value")
	})

	t.Run("GetAbbreviated_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DecisionLog{}
		obj.Abbreviated = nil

		// Act & Assert
		assert.Nil(t, obj.GetAbbreviated(), "getter should return nil when property is nil")
	})

	t.Run("GetAbbreviated_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *DecisionLog
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetAbbreviated() // Should return zero value
	})

}

func TestSettersMarkExplicitDecisionLog(t *testing.T) {
	t.Run("SetTimestamp_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DecisionLog{}
		var fernTestValueTimestamp *time.Time

		// Act
		obj.SetTimestamp(fernTestValueTimestamp)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetName_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DecisionLog{}
		var fernTestValueName *string

		// Act
		obj.SetName(fernTestValueName)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetEndpoint_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DecisionLog{}
		var fernTestValueEndpoint *string

		// Act
		obj.SetEndpoint(fernTestValueEndpoint)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetStatus_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DecisionLog{}
		var fernTestValueStatus *int

		// Act
		obj.SetStatus(fernTestValueStatus)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetRequest_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DecisionLog{}
		var fernTestValueRequest *DecisionLogRequest

		// Act
		obj.SetRequest(fernTestValueRequest)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetResponse_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DecisionLog{}
		var fernTestValueResponse *DecisionLogResponse

		// Act
		obj.SetResponse(fernTestValueResponse)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetDecision_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DecisionLog{}
		var fernTestValueDecision map[string]any

		// Act
		obj.SetDecision(fernTestValueDecision)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetTraceID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DecisionLog{}
		var fernTestValueTraceID *string

		// Act
		obj.SetTraceID(fernTestValueTraceID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPathTrace_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DecisionLog{}
		var fernTestValuePathTrace *DecisionLogPathTrace

		// Act
		obj.SetPathTrace(fernTestValuePathTrace)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetMatchedItems_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DecisionLog{}
		var fernTestValueMatchedItems []int

		// Act
		obj.SetMatchedItems(fernTestValueMatchedItems)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetError_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DecisionLog{}
		var fernTestValueError *string

		// Act
		obj.SetError(fernTestValueError)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetAbbreviated_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DecisionLog{}
		var fernTestValueAbbreviated *bool

		// Act
		obj.SetAbbreviated(fernTestValueAbbreviated)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestGettersDecisionLogPathTrace(t *testing.T) {
	t.Run("GetStringUnknownMap", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DecisionLogPathTrace{}
		var expected map[string]any
		obj.StringUnknownMap = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetStringUnknownMap(), "getter should return the property value")
	})

	t.Run("GetStringUnknownMap_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DecisionLogPathTrace{}
		obj.StringUnknownMap = nil

		// Act & Assert
		assert.Nil(t, obj.GetStringUnknownMap(), "getter should return nil when property is nil")
	})

	t.Run("GetStringUnknownMap_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *DecisionLogPathTrace
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetStringUnknownMap() // Should return zero value
	})

	t.Run("GetStringUnknownMapOptionalList", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DecisionLogPathTrace{}
		var expected []map[string]any
		obj.StringUnknownMapOptionalList = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetStringUnknownMapOptionalList(), "getter should return the property value")
	})

	t.Run("GetStringUnknownMapOptionalList_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DecisionLogPathTrace{}
		obj.StringUnknownMapOptionalList = nil

		// Act & Assert
		assert.Nil(t, obj.GetStringUnknownMapOptionalList(), "getter should return nil when property is nil")
	})

	t.Run("GetStringUnknownMapOptionalList_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *DecisionLogPathTrace
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetStringUnknownMapOptionalList() // Should return zero value
	})

}

func TestGettersDecisionLogRequest(t *testing.T) {
	t.Run("GetStringUnknownMap", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DecisionLogRequest{}
		var expected map[string]any
		obj.StringUnknownMap = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetStringUnknownMap(), "getter should return the property value")
	})

	t.Run("GetStringUnknownMap_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DecisionLogRequest{}
		obj.StringUnknownMap = nil

		// Act & Assert
		assert.Nil(t, obj.GetStringUnknownMap(), "getter should return nil when property is nil")
	})

	t.Run("GetStringUnknownMap_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *DecisionLogRequest
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetStringUnknownMap() // Should return zero value
	})

	t.Run("GetStringUnknownMapList", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DecisionLogRequest{}
		var expected []map[string]any
		obj.StringUnknownMapList = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetStringUnknownMapList(), "getter should return the property value")
	})

	t.Run("GetStringUnknownMapList_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DecisionLogRequest{}
		obj.StringUnknownMapList = nil

		// Act & Assert
		assert.Nil(t, obj.GetStringUnknownMapList(), "getter should return nil when property is nil")
	})

	t.Run("GetStringUnknownMapList_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *DecisionLogRequest
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetStringUnknownMapList() // Should return zero value
	})

}

func TestSettersDecisionLogResponse(t *testing.T) {
	t.Run("SetData", func(t *testing.T) {
		obj := &DecisionLogResponse{}
		var fernTestValueData []*DecisionLog
		obj.SetData(fernTestValueData)
		assert.Equal(t, fernTestValueData, obj.Data)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetCursor", func(t *testing.T) {
		obj := &DecisionLogResponse{}
		var fernTestValueCursor *string
		obj.SetCursor(fernTestValueCursor)
		assert.Equal(t, fernTestValueCursor, obj.Cursor)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetCount", func(t *testing.T) {
		obj := &DecisionLogResponse{}
		var fernTestValueCount *int
		obj.SetCount(fernTestValueCount)
		assert.Equal(t, fernTestValueCount, obj.Count)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersDecisionLogResponse(t *testing.T) {
	t.Run("GetData", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DecisionLogResponse{}
		var expected []*DecisionLog
		obj.Data = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetData(), "getter should return the property value")
	})

	t.Run("GetData_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DecisionLogResponse{}
		obj.Data = nil

		// Act & Assert
		assert.Nil(t, obj.GetData(), "getter should return nil when property is nil")
	})

	t.Run("GetData_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *DecisionLogResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetData() // Should return zero value
	})

	t.Run("GetCursor", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DecisionLogResponse{}
		var expected *string
		obj.Cursor = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetCursor(), "getter should return the property value")
	})

	t.Run("GetCursor_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DecisionLogResponse{}
		obj.Cursor = nil

		// Act & Assert
		assert.Nil(t, obj.GetCursor(), "getter should return nil when property is nil")
	})

	t.Run("GetCursor_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *DecisionLogResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetCursor() // Should return zero value
	})

	t.Run("GetCount", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DecisionLogResponse{}
		var expected *int
		obj.Count = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetCount(), "getter should return the property value")
	})

	t.Run("GetCount_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DecisionLogResponse{}
		obj.Count = nil

		// Act & Assert
		assert.Nil(t, obj.GetCount(), "getter should return nil when property is nil")
	})

	t.Run("GetCount_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *DecisionLogResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetCount() // Should return zero value
	})

}

func TestSettersMarkExplicitDecisionLogResponse(t *testing.T) {
	t.Run("SetData_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DecisionLogResponse{}
		var fernTestValueData []*DecisionLog

		// Act
		obj.SetData(fernTestValueData)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetCursor_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DecisionLogResponse{}
		var fernTestValueCursor *string

		// Act
		obj.SetCursor(fernTestValueCursor)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetCount_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DecisionLogResponse{}
		var fernTestValueCount *int

		// Act
		obj.SetCount(fernTestValueCount)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestJSONMarshalingDecisionLog(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DecisionLog{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled DecisionLog
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj DecisionLog
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj DecisionLog
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingDecisionLogResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DecisionLogResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled DecisionLogResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj DecisionLogResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj DecisionLogResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestStringDecisionLog(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &DecisionLog{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *DecisionLog
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringDecisionLogResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &DecisionLogResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *DecisionLogResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestEnumQueryDecisionsRequestCount(t *testing.T) {
	t.Run("NewFromString_true", func(t *testing.T) {
		t.Parallel()
		val, err := NewQueryDecisionsRequestCountFromString("true")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, QueryDecisionsRequestCount("true"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_false", func(t *testing.T) {
		t.Parallel()
		val, err := NewQueryDecisionsRequestCountFromString("false")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, QueryDecisionsRequestCount("false"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewQueryDecisionsRequestCountFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewQueryDecisionsRequestCountFromString("true")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}

func TestEnumQueryDecisionsRequestIncludeTraces(t *testing.T) {
	t.Run("NewFromString_true", func(t *testing.T) {
		t.Parallel()
		val, err := NewQueryDecisionsRequestIncludeTracesFromString("true")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, QueryDecisionsRequestIncludeTraces("true"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_false", func(t *testing.T) {
		t.Parallel()
		val, err := NewQueryDecisionsRequestIncludeTracesFromString("false")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, QueryDecisionsRequestIncludeTraces("false"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewQueryDecisionsRequestIncludeTracesFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewQueryDecisionsRequestIncludeTracesFromString("true")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}

func TestEnumQueryDecisionsRequestOrder(t *testing.T) {
	t.Run("NewFromString_asc", func(t *testing.T) {
		t.Parallel()
		val, err := NewQueryDecisionsRequestOrderFromString("asc")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, QueryDecisionsRequestOrder("asc"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_desc", func(t *testing.T) {
		t.Parallel()
		val, err := NewQueryDecisionsRequestOrderFromString("desc")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, QueryDecisionsRequestOrder("desc"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewQueryDecisionsRequestOrderFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewQueryDecisionsRequestOrderFromString("asc")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}

func TestEnumQueryDecisionsRequestSort(t *testing.T) {
	t.Run("NewFromString_time", func(t *testing.T) {
		t.Parallel()
		val, err := NewQueryDecisionsRequestSortFromString("time")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, QueryDecisionsRequestSort("time"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_name", func(t *testing.T) {
		t.Parallel()
		val, err := NewQueryDecisionsRequestSortFromString("name")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, QueryDecisionsRequestSort("name"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_status", func(t *testing.T) {
		t.Parallel()
		val, err := NewQueryDecisionsRequestSortFromString("status")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, QueryDecisionsRequestSort("status"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_type", func(t *testing.T) {
		t.Parallel()
		val, err := NewQueryDecisionsRequestSortFromString("type")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, QueryDecisionsRequestSort("type"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewQueryDecisionsRequestSortFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewQueryDecisionsRequestSortFromString("time")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}

func TestExtraPropertiesDecisionLog(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &DecisionLog{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *DecisionLog
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesDecisionLogResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &DecisionLogResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *DecisionLogResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}
