// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
	time "time"
)

func TestSettersCreateUserRequest(t *testing.T) {
	t.Run("SetEmail", func(t *testing.T) {
		obj := &CreateUserRequest{}
		var fernTestValueEmail string
		obj.SetEmail(fernTestValueEmail)
		assert.Equal(t, fernTestValueEmail, obj.Email)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPassword", func(t *testing.T) {
		obj := &CreateUserRequest{}
		var fernTestValuePassword string
		obj.SetPassword(fernTestValuePassword)
		assert.Equal(t, fernTestValuePassword, obj.Password)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetName", func(t *testing.T) {
		obj := &CreateUserRequest{}
		var fernTestValueName *string
		obj.SetName(fernTestValueName)
		assert.Equal(t, fernTestValueName, obj.Name)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetRole", func(t *testing.T) {
		obj := &CreateUserRequest{}
		var fernTestValueRole *string
		obj.SetRole(fernTestValueRole)
		assert.Equal(t, fernTestValueRole, obj.Role)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetUserGroups", func(t *testing.T) {
		obj := &CreateUserRequest{}
		var fernTestValueUserGroups []string
		obj.SetUserGroups(fernTestValueUserGroups)
		assert.Equal(t, fernTestValueUserGroups, obj.UserGroups)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitCreateUserRequest(t *testing.T) {
	t.Run("SetEmail_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateUserRequest{}
		var fernTestValueEmail string

		// Act
		obj.SetEmail(fernTestValueEmail)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPassword_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateUserRequest{}
		var fernTestValuePassword string

		// Act
		obj.SetPassword(fernTestValuePassword)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetName_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateUserRequest{}
		var fernTestValueName *string

		// Act
		obj.SetName(fernTestValueName)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetRole_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateUserRequest{}
		var fernTestValueRole *string

		// Act
		obj.SetRole(fernTestValueRole)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetUserGroups_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateUserRequest{}
		var fernTestValueUserGroups []string

		// Act
		obj.SetUserGroups(fernTestValueUserGroups)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersUserInviteRequest(t *testing.T) {
	t.Run("SetEmail", func(t *testing.T) {
		obj := &UserInviteRequest{}
		var fernTestValueEmail string
		obj.SetEmail(fernTestValueEmail)
		assert.Equal(t, fernTestValueEmail, obj.Email)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetRole", func(t *testing.T) {
		obj := &UserInviteRequest{}
		var fernTestValueRole *UserInviteRequestRole
		obj.SetRole(fernTestValueRole)
		assert.Equal(t, fernTestValueRole, obj.Role)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetUserGroups", func(t *testing.T) {
		obj := &UserInviteRequest{}
		var fernTestValueUserGroups []string
		obj.SetUserGroups(fernTestValueUserGroups)
		assert.Equal(t, fernTestValueUserGroups, obj.UserGroups)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitUserInviteRequest(t *testing.T) {
	t.Run("SetEmail_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UserInviteRequest{}
		var fernTestValueEmail string

		// Act
		obj.SetEmail(fernTestValueEmail)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetRole_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UserInviteRequest{}
		var fernTestValueRole *UserInviteRequestRole

		// Act
		obj.SetRole(fernTestValueRole)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetUserGroups_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UserInviteRequest{}
		var fernTestValueUserGroups []string

		// Act
		obj.SetUserGroups(fernTestValueUserGroups)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersCreateUserResponse(t *testing.T) {
	t.Run("SetMessage", func(t *testing.T) {
		obj := &CreateUserResponse{}
		var fernTestValueMessage *string
		obj.SetMessage(fernTestValueMessage)
		assert.Equal(t, fernTestValueMessage, obj.Message)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetUser", func(t *testing.T) {
		obj := &CreateUserResponse{}
		var fernTestValueUser *CreateUserResponseUser
		obj.SetUser(fernTestValueUser)
		assert.Equal(t, fernTestValueUser, obj.User)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersCreateUserResponse(t *testing.T) {
	t.Run("GetMessage", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateUserResponse{}
		var expected *string
		obj.Message = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetMessage(), "getter should return the property value")
	})

	t.Run("GetMessage_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateUserResponse{}
		obj.Message = nil

		// Act & Assert
		assert.Nil(t, obj.GetMessage(), "getter should return nil when property is nil")
	})

	t.Run("GetMessage_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CreateUserResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetMessage() // Should return zero value
	})

	t.Run("GetUser", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateUserResponse{}
		var expected *CreateUserResponseUser
		obj.User = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetUser(), "getter should return the property value")
	})

	t.Run("GetUser_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateUserResponse{}
		obj.User = nil

		// Act & Assert
		assert.Nil(t, obj.GetUser(), "getter should return nil when property is nil")
	})

	t.Run("GetUser_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CreateUserResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetUser() // Should return zero value
	})

}

func TestSettersMarkExplicitCreateUserResponse(t *testing.T) {
	t.Run("SetMessage_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateUserResponse{}
		var fernTestValueMessage *string

		// Act
		obj.SetMessage(fernTestValueMessage)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetUser_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateUserResponse{}
		var fernTestValueUser *CreateUserResponseUser

		// Act
		obj.SetUser(fernTestValueUser)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersCreateUserResponseUser(t *testing.T) {
	t.Run("SetID", func(t *testing.T) {
		obj := &CreateUserResponseUser{}
		var fernTestValueID *string
		obj.SetID(fernTestValueID)
		assert.Equal(t, fernTestValueID, obj.ID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetEmail", func(t *testing.T) {
		obj := &CreateUserResponseUser{}
		var fernTestValueEmail *string
		obj.SetEmail(fernTestValueEmail)
		assert.Equal(t, fernTestValueEmail, obj.Email)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetName", func(t *testing.T) {
		obj := &CreateUserResponseUser{}
		var fernTestValueName *string
		obj.SetName(fernTestValueName)
		assert.Equal(t, fernTestValueName, obj.Name)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetRole", func(t *testing.T) {
		obj := &CreateUserResponseUser{}
		var fernTestValueRole *string
		obj.SetRole(fernTestValueRole)
		assert.Equal(t, fernTestValueRole, obj.Role)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetUserGroups", func(t *testing.T) {
		obj := &CreateUserResponseUser{}
		var fernTestValueUserGroups []string
		obj.SetUserGroups(fernTestValueUserGroups)
		assert.Equal(t, fernTestValueUserGroups, obj.UserGroups)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetAPIKey", func(t *testing.T) {
		obj := &CreateUserResponseUser{}
		var fernTestValueAPIKey *string
		obj.SetAPIKey(fernTestValueAPIKey)
		assert.Equal(t, fernTestValueAPIKey, obj.APIKey)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersCreateUserResponseUser(t *testing.T) {
	t.Run("GetID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateUserResponseUser{}
		var expected *string
		obj.ID = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetID(), "getter should return the property value")
	})

	t.Run("GetID_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateUserResponseUser{}
		obj.ID = nil

		// Act & Assert
		assert.Nil(t, obj.GetID(), "getter should return nil when property is nil")
	})

	t.Run("GetID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CreateUserResponseUser
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetID() // Should return zero value
	})

	t.Run("GetEmail", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateUserResponseUser{}
		var expected *string
		obj.Email = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetEmail(), "getter should return the property value")
	})

	t.Run("GetEmail_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateUserResponseUser{}
		obj.Email = nil

		// Act & Assert
		assert.Nil(t, obj.GetEmail(), "getter should return nil when property is nil")
	})

	t.Run("GetEmail_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CreateUserResponseUser
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetEmail() // Should return zero value
	})

	t.Run("GetName", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateUserResponseUser{}
		var expected *string
		obj.Name = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetName(), "getter should return the property value")
	})

	t.Run("GetName_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateUserResponseUser{}
		obj.Name = nil

		// Act & Assert
		assert.Nil(t, obj.GetName(), "getter should return nil when property is nil")
	})

	t.Run("GetName_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CreateUserResponseUser
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetName() // Should return zero value
	})

	t.Run("GetRole", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateUserResponseUser{}
		var expected *string
		obj.Role = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetRole(), "getter should return the property value")
	})

	t.Run("GetRole_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateUserResponseUser{}
		obj.Role = nil

		// Act & Assert
		assert.Nil(t, obj.GetRole(), "getter should return nil when property is nil")
	})

	t.Run("GetRole_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CreateUserResponseUser
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetRole() // Should return zero value
	})

	t.Run("GetUserGroups", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateUserResponseUser{}
		var expected []string
		obj.UserGroups = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetUserGroups(), "getter should return the property value")
	})

	t.Run("GetUserGroups_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateUserResponseUser{}
		obj.UserGroups = nil

		// Act & Assert
		assert.Nil(t, obj.GetUserGroups(), "getter should return nil when property is nil")
	})

	t.Run("GetUserGroups_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CreateUserResponseUser
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetUserGroups() // Should return zero value
	})

	t.Run("GetAPIKey", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateUserResponseUser{}
		var expected *string
		obj.APIKey = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetAPIKey(), "getter should return the property value")
	})

	t.Run("GetAPIKey_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateUserResponseUser{}
		obj.APIKey = nil

		// Act & Assert
		assert.Nil(t, obj.GetAPIKey(), "getter should return nil when property is nil")
	})

	t.Run("GetAPIKey_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CreateUserResponseUser
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetAPIKey() // Should return zero value
	})

}

func TestSettersMarkExplicitCreateUserResponseUser(t *testing.T) {
	t.Run("SetID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateUserResponseUser{}
		var fernTestValueID *string

		// Act
		obj.SetID(fernTestValueID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetEmail_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateUserResponseUser{}
		var fernTestValueEmail *string

		// Act
		obj.SetEmail(fernTestValueEmail)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetName_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateUserResponseUser{}
		var fernTestValueName *string

		// Act
		obj.SetName(fernTestValueName)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetRole_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateUserResponseUser{}
		var fernTestValueRole *string

		// Act
		obj.SetRole(fernTestValueRole)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetUserGroups_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateUserResponseUser{}
		var fernTestValueUserGroups []string

		// Act
		obj.SetUserGroups(fernTestValueUserGroups)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetAPIKey_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateUserResponseUser{}
		var fernTestValueAPIKey *string

		// Act
		obj.SetAPIKey(fernTestValueAPIKey)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersUserDetail(t *testing.T) {
	t.Run("SetID", func(t *testing.T) {
		obj := &UserDetail{}
		var fernTestValueID *string
		obj.SetID(fernTestValueID)
		assert.Equal(t, fernTestValueID, obj.ID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetEmail", func(t *testing.T) {
		obj := &UserDetail{}
		var fernTestValueEmail *string
		obj.SetEmail(fernTestValueEmail)
		assert.Equal(t, fernTestValueEmail, obj.Email)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetName", func(t *testing.T) {
		obj := &UserDetail{}
		var fernTestValueName *string
		obj.SetName(fernTestValueName)
		assert.Equal(t, fernTestValueName, obj.Name)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetAPIKey", func(t *testing.T) {
		obj := &UserDetail{}
		var fernTestValueAPIKey *string
		obj.SetAPIKey(fernTestValueAPIKey)
		assert.Equal(t, fernTestValueAPIKey, obj.APIKey)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetRole", func(t *testing.T) {
		obj := &UserDetail{}
		var fernTestValueRole *string
		obj.SetRole(fernTestValueRole)
		assert.Equal(t, fernTestValueRole, obj.Role)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetUserGroups", func(t *testing.T) {
		obj := &UserDetail{}
		var fernTestValueUserGroups []string
		obj.SetUserGroups(fernTestValueUserGroups)
		assert.Equal(t, fernTestValueUserGroups, obj.UserGroups)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetJoinedAt", func(t *testing.T) {
		obj := &UserDetail{}
		var fernTestValueJoinedAt *time.Time
		obj.SetJoinedAt(fernTestValueJoinedAt)
		assert.Equal(t, fernTestValueJoinedAt, obj.JoinedAt)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersUserDetail(t *testing.T) {
	t.Run("GetID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UserDetail{}
		var expected *string
		obj.ID = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetID(), "getter should return the property value")
	})

	t.Run("GetID_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UserDetail{}
		obj.ID = nil

		// Act & Assert
		assert.Nil(t, obj.GetID(), "getter should return nil when property is nil")
	})

	t.Run("GetID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *UserDetail
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetID() // Should return zero value
	})

	t.Run("GetEmail", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UserDetail{}
		var expected *string
		obj.Email = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetEmail(), "getter should return the property value")
	})

	t.Run("GetEmail_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UserDetail{}
		obj.Email = nil

		// Act & Assert
		assert.Nil(t, obj.GetEmail(), "getter should return nil when property is nil")
	})

	t.Run("GetEmail_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *UserDetail
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetEmail() // Should return zero value
	})

	t.Run("GetName", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UserDetail{}
		var expected *string
		obj.Name = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetName(), "getter should return the property value")
	})

	t.Run("GetName_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UserDetail{}
		obj.Name = nil

		// Act & Assert
		assert.Nil(t, obj.GetName(), "getter should return nil when property is nil")
	})

	t.Run("GetName_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *UserDetail
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetName() // Should return zero value
	})

	t.Run("GetAPIKey", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UserDetail{}
		var expected *string
		obj.APIKey = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetAPIKey(), "getter should return the property value")
	})

	t.Run("GetAPIKey_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UserDetail{}
		obj.APIKey = nil

		// Act & Assert
		assert.Nil(t, obj.GetAPIKey(), "getter should return nil when property is nil")
	})

	t.Run("GetAPIKey_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *UserDetail
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetAPIKey() // Should return zero value
	})

	t.Run("GetRole", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UserDetail{}
		var expected *string
		obj.Role = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetRole(), "getter should return the property value")
	})

	t.Run("GetRole_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UserDetail{}
		obj.Role = nil

		// Act & Assert
		assert.Nil(t, obj.GetRole(), "getter should return nil when property is nil")
	})

	t.Run("GetRole_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *UserDetail
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetRole() // Should return zero value
	})

	t.Run("GetUserGroups", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UserDetail{}
		var expected []string
		obj.UserGroups = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetUserGroups(), "getter should return the property value")
	})

	t.Run("GetUserGroups_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UserDetail{}
		obj.UserGroups = nil

		// Act & Assert
		assert.Nil(t, obj.GetUserGroups(), "getter should return nil when property is nil")
	})

	t.Run("GetUserGroups_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *UserDetail
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetUserGroups() // Should return zero value
	})

	t.Run("GetJoinedAt", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UserDetail{}
		var expected *time.Time
		obj.JoinedAt = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetJoinedAt(), "getter should return the property value")
	})

	t.Run("GetJoinedAt_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UserDetail{}
		obj.JoinedAt = nil

		// Act & Assert
		assert.Nil(t, obj.GetJoinedAt(), "getter should return nil when property is nil")
	})

	t.Run("GetJoinedAt_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *UserDetail
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetJoinedAt() // Should return zero value
	})

}

func TestSettersMarkExplicitUserDetail(t *testing.T) {
	t.Run("SetID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UserDetail{}
		var fernTestValueID *string

		// Act
		obj.SetID(fernTestValueID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetEmail_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UserDetail{}
		var fernTestValueEmail *string

		// Act
		obj.SetEmail(fernTestValueEmail)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetName_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UserDetail{}
		var fernTestValueName *string

		// Act
		obj.SetName(fernTestValueName)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetAPIKey_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UserDetail{}
		var fernTestValueAPIKey *string

		// Act
		obj.SetAPIKey(fernTestValueAPIKey)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetRole_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UserDetail{}
		var fernTestValueRole *string

		// Act
		obj.SetRole(fernTestValueRole)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetUserGroups_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UserDetail{}
		var fernTestValueUserGroups []string

		// Act
		obj.SetUserGroups(fernTestValueUserGroups)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetJoinedAt_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UserDetail{}
		var fernTestValueJoinedAt *time.Time

		// Act
		obj.SetJoinedAt(fernTestValueJoinedAt)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersUserInviteResponse(t *testing.T) {
	t.Run("SetMessage", func(t *testing.T) {
		obj := &UserInviteResponse{}
		var fernTestValueMessage *string
		obj.SetMessage(fernTestValueMessage)
		assert.Equal(t, fernTestValueMessage, obj.Message)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetUser", func(t *testing.T) {
		obj := &UserInviteResponse{}
		var fernTestValueUser *UserInviteResponseUser
		obj.SetUser(fernTestValueUser)
		assert.Equal(t, fernTestValueUser, obj.User)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersUserInviteResponse(t *testing.T) {
	t.Run("GetMessage", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UserInviteResponse{}
		var expected *string
		obj.Message = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetMessage(), "getter should return the property value")
	})

	t.Run("GetMessage_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UserInviteResponse{}
		obj.Message = nil

		// Act & Assert
		assert.Nil(t, obj.GetMessage(), "getter should return nil when property is nil")
	})

	t.Run("GetMessage_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *UserInviteResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetMessage() // Should return zero value
	})

	t.Run("GetUser", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UserInviteResponse{}
		var expected *UserInviteResponseUser
		obj.User = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetUser(), "getter should return the property value")
	})

	t.Run("GetUser_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UserInviteResponse{}
		obj.User = nil

		// Act & Assert
		assert.Nil(t, obj.GetUser(), "getter should return nil when property is nil")
	})

	t.Run("GetUser_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *UserInviteResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetUser() // Should return zero value
	})

}

func TestSettersMarkExplicitUserInviteResponse(t *testing.T) {
	t.Run("SetMessage_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UserInviteResponse{}
		var fernTestValueMessage *string

		// Act
		obj.SetMessage(fernTestValueMessage)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetUser_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UserInviteResponse{}
		var fernTestValueUser *UserInviteResponseUser

		// Act
		obj.SetUser(fernTestValueUser)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersUserInviteResponseUser(t *testing.T) {
	t.Run("SetEmail", func(t *testing.T) {
		obj := &UserInviteResponseUser{}
		var fernTestValueEmail *string
		obj.SetEmail(fernTestValueEmail)
		assert.Equal(t, fernTestValueEmail, obj.Email)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetRole", func(t *testing.T) {
		obj := &UserInviteResponseUser{}
		var fernTestValueRole *string
		obj.SetRole(fernTestValueRole)
		assert.Equal(t, fernTestValueRole, obj.Role)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetUserGroups", func(t *testing.T) {
		obj := &UserInviteResponseUser{}
		var fernTestValueUserGroups []string
		obj.SetUserGroups(fernTestValueUserGroups)
		assert.Equal(t, fernTestValueUserGroups, obj.UserGroups)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersUserInviteResponseUser(t *testing.T) {
	t.Run("GetEmail", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UserInviteResponseUser{}
		var expected *string
		obj.Email = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetEmail(), "getter should return the property value")
	})

	t.Run("GetEmail_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UserInviteResponseUser{}
		obj.Email = nil

		// Act & Assert
		assert.Nil(t, obj.GetEmail(), "getter should return nil when property is nil")
	})

	t.Run("GetEmail_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *UserInviteResponseUser
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetEmail() // Should return zero value
	})

	t.Run("GetRole", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UserInviteResponseUser{}
		var expected *string
		obj.Role = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetRole(), "getter should return the property value")
	})

	t.Run("GetRole_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UserInviteResponseUser{}
		obj.Role = nil

		// Act & Assert
		assert.Nil(t, obj.GetRole(), "getter should return nil when property is nil")
	})

	t.Run("GetRole_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *UserInviteResponseUser
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetRole() // Should return zero value
	})

	t.Run("GetUserGroups", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UserInviteResponseUser{}
		var expected []string
		obj.UserGroups = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetUserGroups(), "getter should return the property value")
	})

	t.Run("GetUserGroups_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UserInviteResponseUser{}
		obj.UserGroups = nil

		// Act & Assert
		assert.Nil(t, obj.GetUserGroups(), "getter should return nil when property is nil")
	})

	t.Run("GetUserGroups_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *UserInviteResponseUser
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetUserGroups() // Should return zero value
	})

}

func TestSettersMarkExplicitUserInviteResponseUser(t *testing.T) {
	t.Run("SetEmail_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UserInviteResponseUser{}
		var fernTestValueEmail *string

		// Act
		obj.SetEmail(fernTestValueEmail)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetRole_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UserInviteResponseUser{}
		var fernTestValueRole *string

		// Act
		obj.SetRole(fernTestValueRole)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetUserGroups_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UserInviteResponseUser{}
		var fernTestValueUserGroups []string

		// Act
		obj.SetUserGroups(fernTestValueUserGroups)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestJSONMarshalingCreateUserResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateUserResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled CreateUserResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj CreateUserResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj CreateUserResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingCreateUserResponseUser(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateUserResponseUser{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled CreateUserResponseUser
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj CreateUserResponseUser
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj CreateUserResponseUser
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingUserDetail(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UserDetail{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled UserDetail
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj UserDetail
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj UserDetail
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingUserInviteResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UserInviteResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled UserInviteResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj UserInviteResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj UserInviteResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingUserInviteResponseUser(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UserInviteResponseUser{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled UserInviteResponseUser
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj UserInviteResponseUser
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj UserInviteResponseUser
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestStringCreateUserResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &CreateUserResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CreateUserResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringCreateUserResponseUser(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &CreateUserResponseUser{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CreateUserResponseUser
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringUserDetail(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &UserDetail{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *UserDetail
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringUserInviteResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &UserInviteResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *UserInviteResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringUserInviteResponseUser(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &UserInviteResponseUser{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *UserInviteResponseUser
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestEnumUserInviteRequestRole(t *testing.T) {
	t.Run("NewFromString_admin", func(t *testing.T) {
		t.Parallel()
		val, err := NewUserInviteRequestRoleFromString("admin")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, UserInviteRequestRole("admin"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_editor", func(t *testing.T) {
		t.Parallel()
		val, err := NewUserInviteRequestRoleFromString("editor")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, UserInviteRequestRole("editor"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_developer", func(t *testing.T) {
		t.Parallel()
		val, err := NewUserInviteRequestRoleFromString("developer")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, UserInviteRequestRole("developer"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_custom_role", func(t *testing.T) {
		t.Parallel()
		val, err := NewUserInviteRequestRoleFromString("custom-role")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, UserInviteRequestRole("custom-role"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewUserInviteRequestRoleFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewUserInviteRequestRoleFromString("admin")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}

func TestExtraPropertiesCreateUserResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &CreateUserResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CreateUserResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesCreateUserResponseUser(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &CreateUserResponseUser{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CreateUserResponseUser
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesUserDetail(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &UserDetail{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *UserDetail
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesUserInviteResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &UserInviteResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *UserInviteResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesUserInviteResponseUser(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &UserInviteResponseUser{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *UserInviteResponseUser
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}
