// Code generated by Fern. DO NOT EDIT.

package client

import (
	context "context"
	sdk "sdk"
	assets "sdk/assets"
	relationships "sdk/assets/contexts/relationships"
	core "sdk/core"
	internal "sdk/internal"
	option "sdk/option"
)

type Client struct {
	WithRawResponse *RawClient
	Relationships   *relationships.Client

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		Relationships:   relationships.NewClient(options),
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Retrieve all contexts for the authenticated user. Results are scoped to the API key holder's user groups. Optionally filter by folder name or ID, by user group name or ID when the API key has access to that group, or by name.
func (c *Client) List(
	ctx context.Context,
	request *assets.ListContextsRequest,
	opts ...option.RequestOption,
) (sdk.ContextListResponse, error) {
	response, err := c.WithRawResponse.List(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Create a new context for the authenticated user.
func (c *Client) Create(
	ctx context.Context,
	request *assets.CreateContextRequest,
	opts ...option.RequestOption,
) (*sdk.CreateContextResponse, error) {
	response, err := c.WithRawResponse.Create(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieve a specific context by its ID.
func (c *Client) Get(
	ctx context.Context,
	request *assets.GetContextsRequest,
	opts ...option.RequestOption,
) (*sdk.ContextDetail, error) {
	response, err := c.WithRawResponse.Get(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Update an existing context's properties and schema.
func (c *Client) Update(
	ctx context.Context,
	request *assets.UpdateContextRequest,
	opts ...option.RequestOption,
) (*sdk.UpdateContextResponse, error) {
	response, err := c.WithRawResponse.Update(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Delete a specific context and all its instances.
func (c *Client) Delete(
	ctx context.Context,
	request *assets.DeleteContextsRequest,
	opts ...option.RequestOption,
) (*sdk.DeleteContextResponse, error) {
	response, err := c.WithRawResponse.Delete(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
