// Code generated by Fern. DO NOT EDIT.

package tests

import (
	json "encoding/json"
	big "math/big"
	sdk "sdk"
)

var (
	createFlowsRequestFieldSlug = big.NewInt(1 << 0)
)

type CreateFlowsRequest struct {
	// The unique identifier for the resource.
	Slug string                 `json:"-" url:"-"`
	Body *sdk.CreateTestRequest `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CreateFlowsRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetSlug sets the Slug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateFlowsRequest) SetSlug(slug string) {
	c.Slug = slug
	c.require(createFlowsRequestFieldSlug)
}

func (c *CreateFlowsRequest) UnmarshalJSON(data []byte) error {
	body := new(sdk.CreateTestRequest)
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	c.Body = body
	return nil
}

func (c *CreateFlowsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(c.Body)
}

var (
	deleteFlowsRequestFieldSlug   = big.NewInt(1 << 0)
	deleteFlowsRequestFieldTestID = big.NewInt(1 << 1)
)

type DeleteFlowsRequest struct {
	// The unique identifier for the resource.
	Slug string `json:"-" url:"-"`
	// The ID of the test.
	TestID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (d *DeleteFlowsRequest) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetSlug sets the Slug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteFlowsRequest) SetSlug(slug string) {
	d.Slug = slug
	d.require(deleteFlowsRequestFieldSlug)
}

// SetTestID sets the TestID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteFlowsRequest) SetTestID(testID string) {
	d.TestID = testID
	d.require(deleteFlowsRequestFieldTestID)
}

var (
	listFlowsRequestFieldSlug = big.NewInt(1 << 0)
)

type ListFlowsRequest struct {
	// The unique identifier for the resource.
	Slug string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListFlowsRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetSlug sets the Slug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListFlowsRequest) SetSlug(slug string) {
	l.Slug = slug
	l.require(listFlowsRequestFieldSlug)
}
