// Code generated by Fern. DO NOT EDIT.

package tests

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
)

func TestSettersCreateRulesRequest(t *testing.T) {
	t.Run("SetSlug", func(t *testing.T) {
		obj := &CreateRulesRequest{}
		var fernTestValueSlug string
		obj.SetSlug(fernTestValueSlug)
		assert.Equal(t, fernTestValueSlug, obj.Slug)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitCreateRulesRequest(t *testing.T) {
	t.Run("SetSlug_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateRulesRequest{}
		var fernTestValueSlug string

		// Act
		obj.SetSlug(fernTestValueSlug)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersDeleteRulesRequest(t *testing.T) {
	t.Run("SetSlug", func(t *testing.T) {
		obj := &DeleteRulesRequest{}
		var fernTestValueSlug string
		obj.SetSlug(fernTestValueSlug)
		assert.Equal(t, fernTestValueSlug, obj.Slug)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetTestID", func(t *testing.T) {
		obj := &DeleteRulesRequest{}
		var fernTestValueTestID string
		obj.SetTestID(fernTestValueTestID)
		assert.Equal(t, fernTestValueTestID, obj.TestID)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitDeleteRulesRequest(t *testing.T) {
	t.Run("SetSlug_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DeleteRulesRequest{}
		var fernTestValueSlug string

		// Act
		obj.SetSlug(fernTestValueSlug)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetTestID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DeleteRulesRequest{}
		var fernTestValueTestID string

		// Act
		obj.SetTestID(fernTestValueTestID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersListRulesRequest(t *testing.T) {
	t.Run("SetSlug", func(t *testing.T) {
		obj := &ListRulesRequest{}
		var fernTestValueSlug string
		obj.SetSlug(fernTestValueSlug)
		assert.Equal(t, fernTestValueSlug, obj.Slug)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitListRulesRequest(t *testing.T) {
	t.Run("SetSlug_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListRulesRequest{}
		var fernTestValueSlug string

		// Act
		obj.SetSlug(fernTestValueSlug)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}
