// Code generated by Fern. DO NOT EDIT.

package client

import (
	core "sdk/core"
	internal "sdk/internal"
	flows "sdk/tests/flows"
	rules "sdk/tests/rules"
)

type Client struct {
	Rules *rules.Client
	Flows *flows.Client

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		Rules:   rules.NewClient(options),
		Flows:   flows.NewClient(options),
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}
