// Code generated by Fern. DO NOT EDIT.

package assets

import (
	json "encoding/json"
	big "math/big"
	sdk "sdk"
	internal "sdk/internal"
)

var (
	deleteRuleRequestFieldID = big.NewInt(1 << 0)
)

type DeleteRuleRequest struct {
	// The ID of the rule to delete.
	ID string `json:"id" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (d *DeleteRuleRequest) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteRuleRequest) SetID(id string) {
	d.ID = id
	d.require(deleteRuleRequestFieldID)
}

func (d *DeleteRuleRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler DeleteRuleRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*d = DeleteRuleRequest(body)
	return nil
}

func (d *DeleteRuleRequest) MarshalJSON() ([]byte, error) {
	type embed DeleteRuleRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, d.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	listRulesRequestFieldID        = big.NewInt(1 << 0)
	listRulesRequestFieldSlug      = big.NewInt(1 << 1)
	listRulesRequestFieldSearch    = big.NewInt(1 << 2)
	listRulesRequestFieldVersion   = big.NewInt(1 << 3)
	listRulesRequestFieldFolder    = big.NewInt(1 << 4)
	listRulesRequestFieldLabels    = big.NewInt(1 << 5)
	listRulesRequestFieldUserGroup = big.NewInt(1 << 6)
	listRulesRequestFieldName      = big.NewInt(1 << 7)
)

type ListRulesRequest struct {
	// Filter by the exact rule or flow ID.
	ID *string `json:"-" url:"id,omitempty"`
	// Filter by the exact rule or flow slug (case-sensitive).
	Slug *string `json:"-" url:"slug,omitempty"`
	// Match an exact ID or slug, or a case-insensitive substring of the name. Combined with all other filters.
	Search *string `json:"-" url:"search,omitempty"`
	// Select a published version number (e.g. 3), release environment slug (e.g. production), or latest. Requires exactly one asset after all filters and permission checks. Multiple matches or an invalid version return 400; no match, an unpublished asset, or a missing version/release returns 404. The response is still a one-item array.
	Version *string `json:"-" url:"version,omitempty"`
	// Filter results by folder name or folder ID.
	Folder *string `json:"-" url:"folder,omitempty"`
	// Filter results to assets containing all comma-separated labels.
	Labels []*string `json:"-" url:"labels,omitempty"`
	// Filter results by user group name or ID. The value is validated against workspace groups. Admin/unrestricted API keys can request any group-specific view; restricted API keys may only filter to one of their assigned groups and receive a 403 when filtering outside those groups.
	UserGroup *string `json:"-" url:"user_group,omitempty"`
	// Filter results by name using a case-insensitive substring match.
	Name *string `json:"-" url:"name,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListRulesRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListRulesRequest) SetID(id *string) {
	l.ID = id
	l.require(listRulesRequestFieldID)
}

// SetSlug sets the Slug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListRulesRequest) SetSlug(slug *string) {
	l.Slug = slug
	l.require(listRulesRequestFieldSlug)
}

// SetSearch sets the Search field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListRulesRequest) SetSearch(search *string) {
	l.Search = search
	l.require(listRulesRequestFieldSearch)
}

// SetVersion sets the Version field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListRulesRequest) SetVersion(version *string) {
	l.Version = version
	l.require(listRulesRequestFieldVersion)
}

// SetFolder sets the Folder field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListRulesRequest) SetFolder(folder *string) {
	l.Folder = folder
	l.require(listRulesRequestFieldFolder)
}

// SetLabels sets the Labels field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListRulesRequest) SetLabels(labels []*string) {
	l.Labels = labels
	l.require(listRulesRequestFieldLabels)
}

// SetUserGroup sets the UserGroup field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListRulesRequest) SetUserGroup(userGroup *string) {
	l.UserGroup = userGroup
	l.require(listRulesRequestFieldUserGroup)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListRulesRequest) SetName(name *string) {
	l.Name = name
	l.require(listRulesRequestFieldName)
}

var (
	pullRulesRequestFieldID = big.NewInt(1 << 0)
)

type PullRulesRequest struct {
	// The ID of the rule to export.
	ID string `json:"-" url:"id"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (p *PullRulesRequest) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PullRulesRequest) SetID(id string) {
	p.ID = id
	p.require(pullRulesRequestFieldID)
}

var (
	importRuleRequestFieldRule = big.NewInt(1 << 0)
)

type ImportRuleRequest struct {
	Rule *sdk.RuleImportPayload `json:"rule" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (i *ImportRuleRequest) require(field *big.Int) {
	if i.explicitFields == nil {
		i.explicitFields = big.NewInt(0)
	}
	i.explicitFields.Or(i.explicitFields, field)
}

// SetRule sets the Rule field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *ImportRuleRequest) SetRule(rule *sdk.RuleImportPayload) {
	i.Rule = rule
	i.require(importRuleRequestFieldRule)
}

func (i *ImportRuleRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler ImportRuleRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*i = ImportRuleRequest(body)
	return nil
}

func (i *ImportRuleRequest) MarshalJSON() ([]byte, error) {
	type embed ImportRuleRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*i),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, i.explicitFields)
	return json.Marshal(explicitMarshaler)
}
