// Code generated by Fern. DO NOT EDIT.

package contexts_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	require "github.com/stretchr/testify/require"
	http "net/http"
	sdk "sdk"
	client "sdk/client"
	option "sdk/option"
	testing "testing"
)

func ResetWireMockRequests(
	t *testing.T,
) {
	WiremockAdminURL := "http://localhost:8080/__admin"
	_, err := http.Post(WiremockAdminURL+"/requests/reset", "application/json", nil)
	require.NoError(t, err)
}

func VerifyRequestCount(
	t *testing.T,
	method string,
	urlPath string,
	queryParams map[string]string,
	expected int,
) {
	WiremockAdminURL := "http://localhost:8080/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`"}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			reqBody.WriteString(`":{"equalTo":"`)
			reqBody.WriteString(value)
			reqBody.WriteString(`"}`)
			first = false
		}
		reqBody.WriteString("}")
	}
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestContextsGetInstanceWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &sdk.GetInstanceContextsRequest{
		Slug:     "customer",
		Instance: "cust-12345",
	}
	_, invocationErr := client.Contexts.GetInstance(
		context.TODO(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "GET", "/contexts/customer/cust-12345", nil, 1)
}

func TestContextsSubmitWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &sdk.SubmitContextsRequest{
		Slug:     "customer",
		Instance: "cust-12345",
		Body: map[string]any{
			"email": "customer@example.com",
			"age":   30,
		},
	}
	_, invocationErr := client.Contexts.Submit(
		context.TODO(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "POST", "/contexts/customer/cust-12345", nil, 1)
}

func TestContextsDeleteInstanceWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &sdk.DeleteInstanceContextsRequest{
		Slug:     "customer",
		Instance: "cust-12345",
	}
	_, invocationErr := client.Contexts.DeleteInstance(
		context.TODO(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "DELETE", "/contexts/customer/cust-12345", nil, 1)
}

func TestContextsGetHistoryWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &sdk.GetHistoryContextsRequest{
		Slug:     "customer",
		Instance: "cust-12345",
	}
	_, invocationErr := client.Contexts.GetHistory(
		context.TODO(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "GET", "/contexts/customer/cust-12345/history", nil, 1)
}

func TestContextsGetPendingWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &sdk.GetPendingContextsRequest{
		Slug:     "customer",
		Instance: "cust-12345",
	}
	_, invocationErr := client.Contexts.GetPending(
		context.TODO(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "GET", "/contexts/customer/cust-12345/pending", nil, 1)
}

func TestContextsSolveWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &sdk.SolveContextRuleRequest{
		Slug:     "customer",
		Instance: "cust-12345",
		RuleSlug: "eligibility-check",
	}
	_, invocationErr := client.Contexts.Solve(
		context.TODO(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "POST", "/contexts/customer/cust-12345/solve/eligibility-check", nil, 1)
}

func TestContextsCascadeWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &sdk.CascadeContextRequest{
		Slug:     "customer",
		Instance: "cust-12345",
	}
	_, invocationErr := client.Contexts.Cascade(
		context.TODO(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "POST", "/contexts/customer/cust-12345/cascade", nil, 1)
}

func TestContextsExecuteWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &sdk.SolveContextFlowRequest{
		Slug:     "customer",
		Instance: "cust-12345",
		FlowSlug: "onboarding-flow",
	}
	_, invocationErr := client.Contexts.Execute(
		context.TODO(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "POST", "/contexts/customer/cust-12345/flows/onboarding-flow", nil, 1)
}
