// Code generated by Fern. DO NOT EDIT.

package client

import (
	context "context"
	io "io"
	sdk "sdk"
	client "sdk/assets/contexts/client"
	flows "sdk/assets/flows"
	folders "sdk/assets/folders"
	rules "sdk/assets/rules"
	core "sdk/core"
	internal "sdk/internal"
	option "sdk/option"
)

type Client struct {
	WithRawResponse *RawClient
	Rules           *rules.Client
	Flows           *flows.Client
	Folders         *folders.Client
	Contexts        *client.Client

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		Rules:           rules.NewClient(options),
		Flows:           flows.NewClient(options),
		Folders:         folders.NewClient(options),
		Contexts:        client.NewClient(options),
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Get the rule execution usage of your organization.
func (c *Client) GetUsage(
	ctx context.Context,
	opts ...option.RequestOption,
) (*sdk.UsageStatistics, error) {
	response, err := c.WithRawResponse.GetUsage(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Import rules, flows, contexts, and values from a Rulebricks manifest file (*.rbm). Plain JSON remains supported, and clients may send the same JSON envelope gzip-compressed with `Content-Type: application/octet-stream` and `X-Rulebricks-Content-Encoding: gzip`.
func (c *Client) ImportRbm(
	ctx context.Context,
	request io.Reader,
	opts ...option.RequestOption,
) (*sdk.ImportRbmAssetsResponse, error) {
	response, err := c.WithRawResponse.ImportRbm(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Export selected rules, flows, contexts, and values to a Rulebricks manifest file (*.rbm). Dependencies are resolved automatically: exporting a flow includes its rules, contexts, vocabulary values, and any flows referenced by Run Flow nodes (recursively). Set `compress: true` to receive the manifest in compressed form (a compress-json array). Set `download: true` to receive that manifest directly as a streamed attachment instead of inside the `{ success, manifest }` envelope.
func (c *Client) ExportRbm(
	ctx context.Context,
	request *sdk.ExportManifestRequest,
	opts ...option.RequestOption,
) (*sdk.ExportRbmAssetsResponse, error) {
	response, err := c.WithRawResponse.ExportRbm(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
