// Code generated by Fern. DO NOT EDIT.

package users

import (
	sdk "sdk"
	core "sdk/core"
	internal "sdk/internal"
)

var ErrorCodes internal.ErrorCodes = internal.ErrorCodes{
	500: func(apiError *core.APIError) error {
		return &sdk.InternalServerError{
			APIError: apiError,
		}
	},
	400: func(apiError *core.APIError) error {
		return &sdk.BadRequestError{
			APIError: apiError,
		}
	},
}
