// Code generated by Fern. DO NOT EDIT.

package users

import (
	big "math/big"
)

var (
	createUserGroupRequestFieldName        = big.NewInt(1 << 0)
	createUserGroupRequestFieldDescription = big.NewInt(1 << 1)
)

type CreateUserGroupRequest struct {
	// Unique name of the user group.
	Name string `json:"name" url:"-"`
	// Description of the user group.
	Description *string `json:"description,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CreateUserGroupRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateUserGroupRequest) SetName(name string) {
	c.Name = name
	c.require(createUserGroupRequestFieldName)
}

// SetDescription sets the Description field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateUserGroupRequest) SetDescription(description *string) {
	c.Description = description
	c.require(createUserGroupRequestFieldDescription)
}
