// Code generated by Fern. DO NOT EDIT.

package client

import (
	context "context"
	sdk "sdk"
	objects "sdk/contexts/objects"
	relationships "sdk/contexts/relationships"
	core "sdk/core"
	internal "sdk/internal"
	option "sdk/option"
)

type Client struct {
	WithRawResponse *RawClient
	Objects         *objects.Client
	Relationships   *relationships.Client

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		Objects:         objects.NewClient(options),
		Relationships:   relationships.NewClient(options),
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Retrieve the current state of a context instance.
func (c *Client) Get(
	ctx context.Context,
	request *sdk.GetContextsRequest,
	opts ...option.RequestOption,
) (*sdk.ContextInstanceState, error) {
	response, err := c.WithRawResponse.Get(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Submit data to a context instance, creating it if it doesn't exist. May trigger bound rule/flow evaluations.
func (c *Client) Submit(
	ctx context.Context,
	request *sdk.SubmitContextsRequest,
	opts ...option.RequestOption,
) (*sdk.SubmitContextDataResponse, error) {
	response, err := c.WithRawResponse.Submit(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Delete a specific context instance and its history.
func (c *Client) Delete(
	ctx context.Context,
	request *sdk.DeleteContextsRequest,
	opts ...option.RequestOption,
) (*sdk.DeleteContextInstanceResponse, error) {
	response, err := c.WithRawResponse.Delete(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieve the change history for a context instance.
func (c *Client) GetHistory(
	ctx context.Context,
	request *sdk.GetHistoryContextsRequest,
	opts ...option.RequestOption,
) (*sdk.ContextInstanceHistory, error) {
	response, err := c.WithRawResponse.GetHistory(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Get list of rules/flows that need to be evaluated for this instance.
func (c *Client) GetPending(
	ctx context.Context,
	request *sdk.GetPendingContextsRequest,
	opts ...option.RequestOption,
) (*sdk.ContextInstancePendingResponse, error) {
	response, err := c.WithRawResponse.GetPending(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Re-evaluate registered pending rule and flow executions for this instance after their fact or relationship dependencies may have become available. This does not run every bound asset.
func (c *Client) Cascade(
	ctx context.Context,
	request *sdk.CascadeContextsRequest,
	opts ...option.RequestOption,
) (*sdk.CascadeContextResponse, error) {
	response, err := c.WithRawResponse.Cascade(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Submit an array of records to any context in one synchronous call. Records merge into their context instances (matched by the context's identity fact), bound rules and flows whose inputs became satisfied execute, and the response returns the resolved state of every touched instance. Retries are always safe: merges are idempotent and executions are deduplicated by input hash. Fact history is recorded for tracked facts exactly as on individual writes. Clients chunk large datasets across requests.
func (c *Client) BulkIngest(
	ctx context.Context,
	request *sdk.BulkIngestContextsRequest,
	opts ...option.RequestOption,
) (*sdk.ContextBatchResponse, error) {
	response, err := c.WithRawResponse.BulkIngest(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
