// Code generated by Fern. DO NOT EDIT.

package rules

import (
	context "context"
	sdk "sdk"
	assets "sdk/assets"
	core "sdk/core"
	internal "sdk/internal"
	option "sdk/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Delete a specific rule by its ID.
func (c *Client) Delete(
	ctx context.Context,
	request *assets.DeleteRuleRequest,
	opts ...option.RequestOption,
) (*sdk.SuccessMessage, error) {
	response, err := c.WithRawResponse.Delete(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Export a specific rule by its ID.
func (c *Client) Pull(
	ctx context.Context,
	request *assets.PullRulesRequest,
	opts ...option.RequestOption,
) (sdk.RuleExport, error) {
	response, err := c.WithRawResponse.Pull(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Import a rule into the user's account.
func (c *Client) Push(
	ctx context.Context,
	request *assets.ImportRuleRequest,
	opts ...option.RequestOption,
) (sdk.RuleExport, error) {
	response, err := c.WithRawResponse.Push(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// List all rules in the organization. Optionally filter by folder name or ID.
func (c *Client) List(
	ctx context.Context,
	request *assets.ListRulesRequest,
	opts ...option.RequestOption,
) (sdk.RuleListResponse, error) {
	response, err := c.WithRawResponse.List(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
