name: Go

on:
  push:
    branches: [ init-go-sdk ]
  pull_request:
    branches: [ init-go-sdk ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16' # The Go version to download (if necessary) and use.
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Get dependencies
      run: go get -v -t -d ./...
    - name: Build
      run: go build -v ./...
    - name: Test
      run: go test -v ./...
